### ISSUE TITLE
Missing LICENSE file

### ISSUE THREAD

**Issue by dessant** [kivy-garden/garden.segment#1]
Garden repositories must be released under the MIT license. Please tell us if you agree to release it with this license, or simply add the file, following this template: https://github.com/kivy-garden/kivy-garden.github.io/blob/master/LICENSE.

**Comment by jhautefeuille** [comment]
Hello,

I'm agree with MIT license. It's ok for me.

J.H

**Comment by dessant** [comment]
Thanks, I'm adding the license file.

**Comment by dessant** [comment]
@jhautefeuille, does it apply to https://github.com/kivy-garden/garden.gauge?

**Comment by jhautefeuille** [comment]
Yes you can for all my works relative to Kivy...

**Comment by dessant** [comment]
Great, thanks a lot.
